name: Preprocess Sass

on:
  push:
    paths:
      - '**.scss'
  pull_request:
    paths:
      - '**.scss'

jobs:
  preprocess-sass:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Make destination directory for compiled CSS
        run: mkdir -p /tmp/assets/css/frontend/linguagem

      - name: Preprocess style.scss for each page
        uses: gha-utilities/sass-build@v0.4.7
        with:
          source: |
            frontend/style.scss
            frontend/linguagem/style.scss
          destination: |
            /tmp/assets/css/frontend/style.css
            /tmp/assets/css/frontend/linguagem/style.css
